import { TSESTree } from "@typescript-eslint/experimental-utils";

const getFunctions: Set<string> = new Set([
  "getDataCommonPostprocess",
  "getRange",
  "getActiveCell",
  "getActiveChart",
  "getActiveSlicer",
  "getIsActiveCollabSession",
  "getSelectedRange",
  "getSelectedRanges",
  "getCell",
  "getNext",
  "getPrevious",
  "getRangeByIndexes",
  "getRanges",
  "getUsedRange",
  "getActiveWorksheet",
  "getCount",
  "getFirst",
  "getItem",
  "getLast",
  "getLocation",
  "getAbsoluteResizedRange",
  "getBoundingRect",
  "getCellProperties",
  "getColumn",
  "getColumnProperties",
  "getColumnsAfter",
  "getColumnsBefore",
  "getDirectPrecedents",
  "getEntireColumn",
  "getEntireRow",
  "getExtendedRange",
  "getImage",
  "getIntersection",
  "getLastCell",
  "getLastColumn",
  "getLastRow",
  "getMergedAreas",
  "getOffsetRange",
  "getPivotTables",
  "getRangeEdge",
  "getResizedRange",
  "getRow",
  "getRowProperties",
  "getRowsAbove",
  "getRowsBelow",
  "getSpecialCells",
  "getSpillParent",
  "getSpillingToRange",
  "getSurroundingRegion",
  "getTables",
  "getVisibleView",
  "getEntireColumn",
  "getEntireRow",
  "getIntersection",
  "getOffsetRangeAreas",
  "getSpecialCells",
  "getUsedRangeAreas",
  "getRangeAreasBySheet",
  "getItemAt",
  "getText",
  "getDataBodyRange",
  "GetHeaderRowRange",
  "getSubstring",
  "getTotalRowRange",
  "getInvalidCells",
  "getDimensionValues",
  "getByNamespace",
  "getXml",
  "getColumnLabelRange",
  "getDataHierarchy",
  "getFilterAxisRange",
  "getPivotItems",
  "getRowLabelRange",
  "getDefault",
  "getPrintArea",
  "getPrintTitleColumns",
  "getPrintTitleRows",
  "getParentComment",
  "getAsImage",
  "getActivePage",
  "GetStencilInfo",
  "getBase64Image",
  "getHtml",
  "getParagraphInfo",
  "getByTitle",
  "getRestApiId",
  "getByName",
  "getWindowSize",
  "getActiveSectionOrNull",
  "getActiveSection",
  "getActiveParagraphOrNull",
  "getActiveParagraph",
  "getActivePageOrNull",
  "getActivePage",
  "getActiveOutlineOrNull",
  "getActiveOutline",
  "getActiveNotebookOrNull",
  "getActiveNotebook",
  "getCellPadding",
  "getBorder",
  "getParagraphBefore",
  "getParagraphAfter",
  "getHeader",
  "getFooter",
  "getTextRanges",
  "getOoxml",
  "getNextTextRange",
  "getHyperlinkRanges",
  "getDescendants",
  "getAncestor",
  "getById",
  "getLevelString",
  "getLevelParagraphs",
  "getBase64ImageSrc",
  "getSelection",
  "getByTypes",
  "getByTag",
  "getReferenceId",
  "getDocument",
]);

const getOrNullObjectFunctions: Set<string> = new Set([
  "getRangeOrNullObject",
  "getActiveChartOrNullObject",
  "getActiveSlicerOrNullObject",
  "getNextOrNullObject",
  "getPreviousOrNullObject",
  "getUsedRangeOrNullObject",
  "getFirstOrNullObject",
  "getItemOrNullObject",
  "getLocationOrNullObject",
  "getIntersectionOrNullObject",
  "getSpecialCellsOrNullObject",
  "getSpillParentOrNullObject",
  "getSpillingToRangeOrNullObject",
  "getIntersectionOrNullObject",
  "getSpecialCellsOrNullObject",
  "getUsedRangeAreasOrNullObject",
  "getRangeAreasOrNullObjectBySheet",
  "getInvalidCellsOrNullObject",
  "getPrintAreaOrNullObject",
  "getPrintTitleColumnsOrNullObject",
  "getPrintTitleRowsOrNullObject",
  "getParagraphBeforeOrNullObject",
  "getParagraphAfterOrNullObject",
  "getCellOrNullObject",
  "getNextTextRangeOrNullObject",
  "getLastOrNullObject",
  "getAncestorOrNullObject",
  "getByIdOrNullObject",
]);

export function isGetFunction(node: TSESTree.Node): boolean {
  return (
    node.type == TSESTree.AST_NODE_TYPES.CallExpression &&
    node.callee.type === TSESTree.AST_NODE_TYPES.MemberExpression &&
    node.callee.property.type === TSESTree.AST_NODE_TYPES.Identifier &&
    (getFunctions.has(node.callee.property.name) ||
      getOrNullObjectFunctions.has(node.callee.property.name))
  );
}

export function isGetOrNullObjectFunction(node: TSESTree.Node): boolean {
  return (
    node.type == TSESTree.AST_NODE_TYPES.CallExpression &&
    node.callee.type === TSESTree.AST_NODE_TYPES.MemberExpression &&
    node.callee.property.type === TSESTree.AST_NODE_TYPES.Identifier &&
    getOrNullObjectFunctions.has(node.callee.property.name)
  );
}

export function isLoadFunction(node: TSESTree.MemberExpression): boolean {
  return (
    node.property.type === TSESTree.AST_NODE_TYPES.Identifier &&
    node.property.name === "load"
  );
}
