# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master

resources:
  repositories:
  - repository: self
    type: git
    ref: master

jobs:
- job: Windows 1903
  pool:
    name: OPX Windows 1903 Dogfood Pool
  steps:
  - checkout: self
  - template: ./steps/npm-install.yaml
  - template: ./steps/build.yaml
  - template: ./steps/run-tests.yaml
  - template: ./steps/cleanup.yaml

- job: Mac
  pool:
    name: OPX Mac Dogfood Pool
  steps:
  - checkout: self
  - template: ./steps/npm-install.yaml
  - template: ./steps/build.yaml
  - template: ./steps/run-tests.yaml
  - template: ./steps/cleanup.yaml

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - checkout: self
  - template: ./steps/npm-install.yaml
  - template: ./steps/build.yaml
  - template: ./steps/run-tests.yaml
  - template: ./steps/cleanup.yaml