# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
- job: Windows
  pool:
    name: OPX Windows 1903 Dogfood Pool
    demands: npm
  steps:
  - template: ./steps/npm-install.yaml
  - template: ./steps/build.yaml
  - template: ./steps/run-tests.yaml
  - template: ./steps/cleanup.yaml

- job: Mac
  pool:
    name: OPX Mac Dogfood Pool
    demands: npm
  steps:
  - template: ./steps/npm-install.yaml
  - template: ./steps/build.yaml
  - template: ./steps/run-tests.yaml
  - template: ./steps/cleanup.yaml

- job: Linux
  pool:
    name: Azure Pipelines
    demands: npm
  steps:
  - template: ./steps/npm-install.yaml
  - template: ./steps/build.yaml
  - template: ./steps/run-tests.yaml
  - template: ./steps/cleanup.yaml