# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
  - job: Windows10Latest
    pool:
      name: OE-OfficeClientApps
    steps:
      - task: Npm@1
        displayName: "Package level npm install"
        inputs:
          command: custom
          customCommand: "run exec -- npm install"
      - template: ./steps/npm-install.yaml
      - template: ./steps/build.yaml
      - template: ./steps/devcerts.yml
      - template: ./steps/edgewebview.yml
      - template: ./steps/test.yml
