# steps:
# - task: Npm@1
#   displayName: "Build"
#   inputs:
#     command: custom
#     customCommand: "run build"

steps:
- powershell: |
    npm run build
  displayName: Build packages
  errorActionPreference: Continue